config/routes.rb
Rails.application.routes.draw do
  get 'quizzes/category'

  match "quizzes/questions" => "quizzes#questions" , via: [:get, :post]

  match "quizzes/score" => "quizzes#score" , via: [:get, :post]

  match "quizzes/answers" => "quizzes#answers" , via: [:get, :post]

  get 'users/new'

  get 'users/profile'

  get 'users/create'

  get 'users/update'

  get 'users/index'

  resources :categories

  resources :scores

  devise_for :users
  resources :questions
  root :to => redirect('/users/profile')

end

app/models/question.rb
class Question < ActiveRecord::Base
	validates :statement,:option1,:option2,:option3,:option4,:answer,:stars,:category_id, presence: true
	belongs_to :category
	attr_accessible :statement,:option1,:option2,:option3,:option4,:answer,:stars,:category_id
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :check_admin
  before_action :set_question, only: [:show, :edit, :update, :destroy]


  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  #Checking if the current user is an admin
    def check_admin
      @user = current_user
      if @user.admin == false
        redirect_to users_profile_path, flash: {alert: "You don't have the permissions to visit the page you are trying to"}
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:statement, :option1, :option2, :option3, :option4, :answer, :stars, :category_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :statement %><br>
    <%= f.text_field :statement %>
  </div>
  <div class="field">
    <%= f.label :option1 %><br>
    <%= f.text_field :option1 %>
  </div>
  <div class="field">
    <%= f.label :option2 %><br>
    <%= f.text_field :option2 %>
  </div>
  <div class="field">
    <%= f.label :option3 %><br>
    <%= f.text_field :option3 %>
  </div>
  <div class="field">
    <%= f.label :option4 %><br>
    <%= f.text_field :option4 %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.number_field :answer %>
  </div>
  <div class="field">
    <%= f.label :stars %><br>
    <%= f.number_field :stars %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Statement</th>
      <th>Option1</th>
      <th>Option2</th>
      <th>Option3</th>
      <th>Option4</th>
      <th>Answer</th>
      <th>Stars</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.statement %></td>
        <td><%= question.option1 %></td>
        <td><%= question.option2 %></td>
        <td><%= question.option3 %></td>
        <td><%= question.option4 %></td>
        <td><%= question.answer %></td>
        <td><%= question.stars %></td>
        <td><%= question.category_id %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Statement:</strong>
  <%= @question.statement %>
</p>

<p>
  <strong>Option1:</strong>
  <%= @question.option1 %>
</p>

<p>
  <strong>Option2:</strong>
  <%= @question.option2 %>
</p>

<p>
  <strong>Option3:</strong>
  <%= @question.option3 %>
</p>

<p>
  <strong>Option4:</strong>
  <%= @question.option4 %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @question.stars %>
</p>

<p>
  <strong>Category:</strong>
  <%= @question.category_id %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>